

server:
  port: 25927
  servlet:
    context-path: '/payments'
---

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://ec2-34-196-238-94.compute-1.amazonaws.com:5432/d7thl6tac0sedq
    username: ubmborzivxpwzr
    password: 8f2e857c9ca0703ad114be7fa1c80f0bea975cfc4607d93017f550b3771d3dcf
    driver-class-name: org.postgresql.Driver
    platform: postgres