
spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    platform: hsqldb
    continue-on-error: false

---

spring:
  profiles: local-mysql-localhost
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/examen?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: Tecso2019
  h2:
    console:
      enabled: true
      
---

spring:
  profiles: local-mysql-container
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql-container:3306/examen?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: Tecso2019
  h2:
    console:
      enabled: true    
